gen_lr: 0.1
discrim_lr: 0.03
gen_steps: 5
discrim_steps: 3
num_samples: 400

_target_: 

train:
   _target_: nanophoto.experiments.gan.gantestraw.gan_training_loop

inference:
   _target_: models.unet.inference
