# Simple UNet model configuration (works with arbitrary image sizes)
name: simple_unet
defaults:
  - /train: simple_unet
  - /inference: simple_unet

_target_: models.simple_unet.SimpleUNet

# Model architecture parameters
input_channels: 1
output_channels: 1
base_channels: 64

# Training parameters  
seed: -1
lr: 0.001
train_set_size: -1  # -1 means use all available data
batch_size: 8
# n_epochs will be computed dynamically as int(n_compute_steps / train_set_size)
