# Standard GAN model configuration
_target_: models.standard_gan.StandardGAN

# Model architecture parameters
latent_dim: 100
img_channels: 1
img_size: 64
hidden_dim: 64

# Training parameters
n_epochs: 200
batch_size: 32
lr_g: 0.0002  # Generator learning rate
lr_d: 0.0002  # Discriminator learning rate
label_smoothing: 0.1  # Label smoothing for discriminator
seed: -1
train_set_size: -1  # -1 means use all available data
n_compute_steps: 2_500_000
