name: unet_small
defaults:
  - /inference: unet_small

n_time_steps: 1000
ema_decay: 0.9999

_target_: models.unet.UNET
Channels: [16, 16]  # Simple 2-layer architecture
Attentions: [False, False]  # No attention
Upscales: [False, True]  # First layer downsamples, second layer upsamples
num_groups: 8  # Divides evenly into 16 
dropout_prob: 0.0  # No dropout
num_heads: 4
input_channels: 1
output_channels: 1
device: 'cuda'
time_steps: 1000

# Training parameters required by unet.train function
n_epochs: 100
lr: 0.00002
batch_size: 8
num_time_steps: 1000
seed: -1
