# VAE model configuration
_target_: models.vae.VAE

# Model architecture parameters
latent_dim: 128
img_channels: 1
img_size: 64
hidden_dim: 64

# Training parameters
n_epochs: 200
batch_size: 32
lr: 0.001
beta: 1.0  # KL weight for β-VAE (1.0 = standard VAE, >1.0 = β-VAE)
seed: -1
train_set_size: -1  # -1 means use all available data
n_compute_steps: 2_500_000
