# WGAN model configuration
_target_: models.wgan.WGAN

# Model architecture parameters
latent_dim: 100
img_channels: 1
img_size: 64  # Will be overridden by actual data size
hidden_dim: 64

# Training parameters
n_epochs: 200
batch_size: 32
lr: 0.0001
n_critic: 5  # Train critic 5 times per generator step
lambda_gp: 10  # Gradient penalty coefficient
seed: -1
train_set_size: -1  # -1 means use all available data
n_compute_steps: 2_500_000
