- _target_: evaluation.ComputeFom
- _target_: evaluation.VisualizeGeneratedSamples
  n_samples: 16
- _target_: evaluation.PlotFomHistogram
- _target_: evaluation.ComputeEntropy
  approach: "metric"
- _target_: evaluation.NNDistanceTrainSet
