# general
debug: True
checkpoint_load_path: ~/repos/diffusion-model/checkpoint.pt
data_path: ~/scratch/nanophoto/topoptim/fulloptim/images.npy
guide_file: ~/repos/diffusion-model/guided_gen/guide.npy
savepath: images
inference_only: False
n_model_parameters: 35_000_000

logger: True

defaults:
  - _self_
  - model: unet
  - inference: unet
  - training: unet

log_level: DEBUG
name: "diff_hpo"

seed: ${oc.env:SLURM_PROCID,123}

algorithm:
  optimizer:
    lr: 0.002
