# Force re-computation of all evaluation functions, even if already computed
force_recompute: false

# Evaluation configuration
evaluation:
  fom:
    _target_: photo_gen.evaluation.evaluation.FOM

functions:
  - _target_: photo_gen.evaluation.evaluation.VisualizeGeneratedSamples
    n_samples: 16
  - _target_: photo_gen.evaluation.evaluation.PlotFomHistogram
  - _target_: photo_gen.evaluation.evaluation.Entropy
    metric: True
  - _target_: photo_gen.evaluation.evaluation.PCAProjPerDimEntropy
    dim: 50
    n_neighbors: 4
    metric: True
  - _target_: photo_gen.evaluation.evaluation.NNDistanceTrainSet
    train_set_path: ~/scratch/nanophoto/topoptim/fulloptim/images.npy
    metric: True
  - _target_: photo_gen.evaluation.evaluation.ImageAverageEntropy
    n_neighbors: 4
    metric: True  
  - _target_: photo_gen.evaluation.evaluation.PairwiseDistanceEntropy
    n_neighbors: 4
    metric: True

datasets:
  - name: diffusion
    path: ${oc.env:SCRATCH}/nanophoto/diffusion/train3/7121883/
    n_samples: 28

  - name: diffusion
    path: ${oc.env:SCRATCH}/nanophoto/diffusion/train3/7121885/
    n_samples: 47

  - name: diffusion
    path: ${oc.env:SCRATCH}/nanophoto/diffusion/train3/7121891/
    n_samples: 97

  - name: diffusion
    path: ${oc.env:SCRATCH}/nanophoto/diffusion/train3/7121888/
    n_samples: 180

  - name: diffusion
    path: ${oc.env:SCRATCH}/nanophoto/diffusion/train3/7121890/
    n_samples: 192

  - name: diffusion
    path: ${oc.env:SCRATCH}/nanophoto/diffusion/train3/7121886/
    n_samples: 261

  - name: diffusion
    path: ${oc.env:SCRATCH}/nanophoto/diffusion/train3/7121889/
    n_samples: 277

  - name: diffusion
    path: ${oc.env:SCRATCH}/nanophoto/diffusion/train3/7212292/
    n_samples: 230

  - name: diffusion
    path: ${oc.env:SCRATCH}/nanophoto/diffusion/train3/7212298/
    n_samples: 52

  - name: diffusion
    path: ${oc.env:SCRATCH}/nanophoto/diffusion/train3/7212299/
    n_samples: 209