defaults:
  - fom: meep
functions:
  - _target_: photo_gen.evaluation.evaluation.VisualizeGeneratedSamples
    n_samples: 16
  - _target_: photo_gen.evaluation.evaluation.PlotFomHistogram
  - _target_: photo_gen.evaluation.evaluation.ComputeEntropy
    metric: True
  - _target_: photo_gen.evaluation.evaluation.NNDistanceTrainSet
    train_set_path: ~/scratch/nanophoto/topoptim/fulloptim/images.npy
    metric: True
